### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by f-person** [Fuelet/flutter_cloud_kit#6]
This will likely be straightforward if both macOS and iOS use the same CloudKit framework (which I believe they do). The Swift code would need to be moved to a separate framework (or just a top-level dir?) and probably symlinked from iOS and macOS targets.
I'm not sure how exactly the final implementation would look like, but I'm willing to work on it if this package ever gets relicensed under a permissive license (e.g., MIT) :)

**Comment by mpoplavkov** [comment]
Hey, thanks for your interest! 

I think, it's a good idea! I just changed the license to MIT, so feel free to contribute to the project.
